name: the configuration of application

develop: &base
  VERSION: 1.0.0
  aiogram:
    API_TOKEN: '123456789:AAAAAAAAAAAAAAAAAaaaAAAAAAAAAAAAAAa'
    WEBHOCK_HOST: localhost
    WEBHOCK_PATH: /
    WEBHOCK_PORT: 3001
    USE_POLLING: true
    PARSE_MOD: html
    SKIP_UPDATES: false
    CHECK_IP: false
    RETRY_AFTER: null
    TIMEOUT: 1
    RELAX: 0.1
    FAST: true

  logging:
    version: 1
    disable_existing_loggers: true
    formatters:
      standard:
        format: '[%(asctime)20s][PID %(process)d:%(threadName)s][%(levelname)s][MESSAGE]: %(message)s'

    handlers:
      console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

    root:
      level: NOTSET
      handlers: [ console ]
      propogate: yes

    loggers:
      app:
        level: INFO
        propogate: no

  i18n:
    path: ''
    domain: ''
    locales: [ ]
    defailt_locale: ''

prodaction:
  <<: *base


testing:
  <<: *base
