name: the configuration of application

develop: &base
  VERSION: 1.0.0
  bot:
    APP_BOT_API_TOKEN: '123456789:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    APP_BOT_WEBHOCK_HOST: localhost
    APP_BOT_WEBHOCK_PATH: /
    APP_BOT_WEBHOCK_PORT: 3001
    APP_BOT_USE_POLLING: true
    APP_BOT_PARSE_MOD: html
    APP_BOT_SKIP_UPDATES: false
    APP_BOT_CHECK_IP: false
    APP_BOT_RETRY_AFTER: null
    APP_BOT_TIMEOUT: 1
    APP_BOT_RELAX: 0.1
    APP_BOT_FAST: true

  logging:
    version: 1
    force: true
    disable_existing_loggers: true
    formatters:
      standard:
        format: '[%(levelname)-7s][%(filename)-15s][%(lineno)4d][MSG]: %(message)s'

    handlers:
      console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

    root:
      level: NOTSET
      handlers: [ console ]
      propogate: yes

    loggers:
      aiogram:
        level : INFO
        propogate: no

      gino:
        level: WARN
        propogate: no

      app:
        level: INFO
        propogate: no

      app.middleware:
        level: DEBUG
        propogate: on

      app.controllers:
        level: DEBUG
        propogate: on

      app.core:
        level: DEBUG
        propogate: no

      app.core.dispatcher:
        level: DEBUG
        propogate: no

      app.ui.interface:
        level: DEBUG
        propogate: no

      app.ui.i18n:
        level: DEBUG
        propogate: no

      app.ui.templates:
        level: DEBUG
        propogate: no

      app.configure:
        level: DEBUG
        propogate: no

      app.configure.reader:
        loevel: INFO
        propogate: no

  i18n:
    APP_LC_PATH: './app/ui/locales'
    APP_LC_DOMAIN: 'app'
    APP_LC_DEFAULT_LOCALE: 'en'

  database:
    APP_DB_DRIVER: 'postgresql'
    APP_DB_PORT: 5432
    APP_DB_HOST: '127.0.0.1'
    APP_DB_USERNAME: 'postgres'
    APP_DB_PASSWORD: 'postgres'
    APP_DB_NAME: 'the_old_farm_db'
    APP_DB_MIN_POOL: 5
    APP_DB_MAX_POOL: 10
    APP_DB_ISOLATION_LEVEL: 'SERIALIZABLE'


prodaction:
  <<: *base


testing:
  <<: *base
