name: the configuration of application

develop: &base
  VERSION: 1.0.0
  aiogram:
    APP_AG_API_TOKEN: '123456789:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    APP_AG_WEBHOCK_HOST: localhost
    APP_AG_WEBHOCK_PATH: /
    APP_AG_WEBHOCK_PORT: 3001
    APP_AG_USE_POLLING: true
    APP_AG_PARSE_MOD: html
    APP_AG_SKIP_UPDATES: false
    APP_AG_CHECK_IP: false
    APP_AG_RETRY_AFTER: null
    APP_AG_TIMEOUT: 1
    APP_AG_RELAX: 0.1
    APP_AG_FAST: true

  logging:
    version: 1
    disable_existing_loggers: true
    formatters:
      standard:
        format: '[%(levelname)-7s][%(funcName)-15s][%(lineno)4d][MSG]: %(message)s'

    handlers:
      console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

    root:
      level: NOTSET
      handlers: [ console ]
      propogate: yes

    loggers:
      aiogram:
        level : INFO
        propogate: no

      app:
        level: INFO
        propogate: no

      app.middleware:
        level: DEBUG
        propogate: on

      app.controllers:
        level: DEBUG
        propogate: on

      app.core:
        level: DEBUG
        propogate: no

      app.core.dispatcher:
        level: DEBUG
        propogate: no

      app.ui.interface:
        level: DEBUG
        propogate: no

      app.ui.i18n:
        level: DEBUG
        propogate: no

      app.ui.templates:
        level: DEBUG
        propogate: no




  i18n:
    APP_LC_PATH: './app/ui/locales'
    APP_LC_DOMAIN: 'app'
    APP_LC_DEFAULT_LOCALE: 'en'

prodaction:
  <<: *base


testing:
  <<: *base
