name: the configuration of application

prod: &base
  logging:
    version: 1
    disable_existing_loggers: true
    formatters:
      standard:
        format: "[%(asctime)20s][PID %(process)d:%(threadName)s][%(name)s][%(levelname)s][MESSAGE]: %(message)s"

    handlers:
      console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

    root:
      level: NOTSET
      handlers: [ console ]
      propogate: yes

    loggers:
      app:
        level: INFO
        propogate: no


develop:
  <<: *base


testing:
  <<: *base
