name: CI
on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches:
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      matrix:
        python-version: ['3.8']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Checking flake8
        run: |
          flake8 ./app/ ./tests/
      - name: Checking pytest
        run: |
          pytest
